// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeApp.Repositories;

namespace TradeApp.Repositories.Migrations
{
    [DbContext(typeof(TradeAppDbContext))]
    [Migration("20210930205205_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeApp.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1Email@mail.ru",
                            FirstName = "User1FirstName",
                            Lastname = "User1LastName"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2Email@mail.ru",
                            FirstName = "User2FirstName",
                            Lastname = "User2LastName"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3Email@mail.ru",
                            FirstName = "User3FirstName",
                            Lastname = "User3LastName"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4Email@mail.ru",
                            FirstName = "User4FirstName",
                            Lastname = "User4LastName"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5Email@mail.ruil",
                            FirstName = "User5FirstName",
                            Lastname = "User5LastName"
                        },
                        new
                        {
                            Id = 6,
                            Email = "user6Email@mail.ru",
                            FirstName = "User6FirstName",
                            Lastname = "User6LastName"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
